// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQX6GsF1bkNhnq4m9Z_AWyyctwZOL4hA',
    appId: '1:338925619861:web:5f410e8a397f806cb3299c',
    messagingSenderId: '338925619861',
    projectId: 'grittracker-721c9',
    authDomain: 'grittracker-721c9.firebaseapp.com',
    storageBucket: 'grittracker-721c9.firebasestorage.app',
    measurementId: 'G-LT169C07B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGjyoVe9X_NK9ehxOf94j0dwM3_x3ozgw',
    appId: '1:338925619861:android:5a9a0fe84ad3d754b3299c',
    messagingSenderId: '338925619861',
    projectId: 'grittracker-721c9',
    storageBucket: 'grittracker-721c9.firebasestorage.app',
  );
}
